version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=pleasechangeme
  filebeat:
    container_name: filebeat
    build: ./builds/filebeat/
    depends_on: 
      - zeek
    restart: always
    volumes:
      -  ./zeek-spool:/zeek-spool
  logstash:
    container_name: logstash
    build: ./builds/logstash/
    restart: always
  zeek:
    container_name: zeek
    build: ./builds/zeek/
    restart: always
    network_mode: "host"
    volumes:
      -  ./zeek-spool:/zeek-spool

# volumes:
#   zeek-spool:
#     external: true
#     mount_point: ./zeek-logs
