version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=pleasechangeme
  fluentd:
    container_name: fluentd
    build: ./builds/fluentd/
    depends_on: 
      - zeek
    restart: always
    volumes:
      -  ./zeek-spool:/zeek-spool
    # environment:
    #     - FLUENT_UID=0
  zeek:
    container_name: zeek
    build: ./builds/zeek/
    restart: always
    network_mode: "host"
    volumes:
      -  ./zeek-spool:/zeek-spool
