version: "3"
services:
  fluentd:
    container_name: fluentd
    build: ./builds/fluentd/
    depends_on: 
      - zeek
    restart: always
    network_mode: "bridge"
    volumes:
      -  zeek-spool-vol:/zeek-spool
    # environment:
    #     - FLUENT_UID=0
  zeek:
    container_name: zeek
    build: ./builds/zeek/
    restart: always
    network_mode: "host"
    volumes:
      -  zeek-spool-vol:/zeek-spool
volumes:
  zeek-spool-vol:
    external: false
