kind: Service
apiVersion: v1
metadata:
    name: rabbitmq-service
spec:
  type: NodePort
  ports:
    - name: rabbitmq-manager
      protocol: TCP
      port: 15672
      nodePort: 30000
    - name: rabbitmq-amqp
      protocol: TCP
      port: 5672
      nodePort: 30001
  selector:
    name: rabbitmq-label
---
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-pod
  labels:
    name: rabbitmq-label
spec:
  containers:
    - name: rabbitmq-container
      image: rabbitmq:3-management
      env:
        - name: RABBITMQ_DEFAULT_USER
          value: "fishy-admin"
        - name: RABBITMQ_DEFAULT_PASS
          value: "pleasechangeme"
